# -*- coding: utf-8 -*-
"""202401100700099_ECE_B

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GcqOHyzmdVfERv2yGlRI21c04fPhWGiG
"""

from tabulate import tabulate


items = []
total = 0

print("Enter grocery items (type 'done' to finish):")
while True:
        name = input("Enter item name: ")
        if name.lower() == 'done':
            break

        try:
            quantity = float(input("Enter quantity: "))
            price = float(input("Enter price per unit: "))
        except ValueError:
            print("Invalid input! Please enter numeric values for quantity and price.")
            continue

        total_price = quantity * price
        total += total_price
        items.append([name, quantity, price, total_price])

print("\nGrocery Bill:")
print(tabulate(items, headers=["Item", "Quantity", "Price per Unit", "Total Price"], tablefmt="fancy_grid"))
print(f"\nGrand Total: ₹{total:.2f}")



